version: "3.9"

services:
  database:
    image: mariadb:10.11.2
    hostname: database
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: zanstore
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin